### PR TITLE
Implementation of login/logout.

### LINKED ISSUE #12: Create a Home View in the Users app
We need to create a homepage for users who login. For now, having a simple html page with a heading `Hello Users!` will suffice. Do ensure to put this html template in the path specified below. Also do create a home view (function-based) to render this html template.

**Tasks**
- [ ] Define a home view in users/views.py
- [ ] Create a `users/templates/users/home.html` (You might have to create this folder)
- [ ] Render home.html in the home view in users/views.py

Note: Do not add the required urls, this will be taken up as a separate issue.

### LINKED ISSUE #13: Add Urls to render Home View
To ensure we can access our Home View in the users app in the browser, we will need to add url links.

**Expected** : localhost:8000/users/ - should display Home View of the users app

**Tasks** 
- [ ] In `users/urls.py` include an empty url to the Home View in `users/views.py`
- [ ] In `crispy_ai/urls.py` import the users urls and include it with the path `users/`

### LINKED ISSUE #14: Register Users App in the list of installed apps
You would need to edit `crispy_ai/settings.py` and add `users.apps.UsersConfig` to the list of Installed apps.

### LINKED ISSUE #16: Login/Logout Authentication
Users need to be able to login to gain access to crispy-powered courses ;)
Here we add simple login/logout functionality using Django's built in features. 

**Tasks**
- [ ] Use Django auth_views to add a Login/Logout view in `crispy_ai/urls.py`
- [ ] Create the templates `users/login.html` and `users/logout.html`
- [ ] Add a LOGIN_REDIRECT_URL to the Home View in settings.py
- [ ] In `users/logout.html` add a link to login again

### LINKED ISSUE #19: Stylish Header
Create a stylish header and put it in 'base.html'

### PR DESCRIPTION
**Pull request by vedangj044**
Closes #12 
Closes #13 
Closes #14 
Closes #16 
Closes #19 
Read commit messages.

### CODE REVIEW

**Comment by vedangj044** [comment]
Created a 'Stylish Header'

**Comment by NeuralFlux** [comment]
Thanks for the PR @vedangj044 . I've found some small bugs, other than that it's perfect. So here are the bugs
- General: There were a few template files in `users/templates` directly, instead of being inside `users/templates/users`. This may seem redundant but it helps in avoiding bugs later on.
- #13 requires `localhost:8000/users/` to display the user home, whereas in the PR `localhost:8000` itself displays the user home. You can try redirecting to login if a user isn't logged in and if they are, redirect to home.
- #14 requires `users.apps.UsersConfig` to be added to the `INSTALLED_APPS`, whereas only `users` is added.
- #16 requires a logout view too, that is, to display an acknowledgement that a user has been logged out which hasn't been implemented. You can make a template html for this.

**Comment by NeuralFlux** [comment]
[This](https://www.youtube.com/watch?v=a48xeeo5Vnk) video on routing might help!

**Comment by vedangj044** [comment]
- We can have only base.html in `users/templates` directly rest everything in `users/templates/users`.

- In this PR, i had made two home.html pages, one routed to `/users/`, other routed to `/` (empty url).
 

- do you want me to redirect the `localhost:8000` to `localhost:8000/users/` and display the homepage ?

In am working on the rest.

**Comment by NeuralFlux** [comment]
There seems to be some problem with the routing, when I go to `localhost:8000`, there's an error saying `ERR_TOO_MANY_REDIRECTS`. I guess there's a routing loop, please look into this.

Also, you're right about the redirection. `localhost:8000/` should redirect to `localhost:8000/users/` if a session is logged in. Else it should redirect to `localhost:8000/users/login` where the user can login. Once logged in, redirect to `localhost:8000/users/` where the User Home is rendered.

**Comment by NeuralFlux** [comment]
The redirection problem persists, is it only me or it happens in your PC too?

**Comment by vedangj044** [comment]
I didn't face `ERR_TOO_MANY_REDIRECTS` up till now.

**Comment by NeuralFlux** [comment]
Some bugs have popped up in my PC I guess, but the problem is I can't merge before reviewing it. Hence I'll take some time to fix it, please don't mind.

**Comment by svp19** [comment]
Woah, @vedangj044 you have done great work...but you should have opened up a separate PR for each issue separately.  Also some GitHub courtesy rules, do not submit PRs to close issues you were not assigned too. 
Wait for @NeuralFlux  to review and decide.

**Comment by vedangj044** [comment]
adding `permanent=False` did solve the `ERR_TOO_MANY_REDIRECTS` issue, but i am not sure how it happened. Kindly, review these change. 
@svp19 Sure, I would keep this in mind.

**Comment by NeuralFlux** [comment]
Amazing work there @vedangj044 . I feel it's ready to be merged.

**Pull request merged**
