### PR TITLE
view for user Registration created 

### PR DESCRIPTION
**Pull request by ayush1999guptA**
- [ ] Closes: #15 
- [ ] Closes: #29 
- [x] PEP8
Changes Summary: Created a new Register view which provides the functionality to register user and also changed the login template. In order to validate the email I have added 2 dependencies:-  py3dns==3.2.0
validate-email==1.3
which I have added to the requirements.txt file

### CODE REVIEW

**Comment by NeuralFlux** [comment]
May I know what's the difference in between this PR and the previous PR, and why did you close it?

**Comment by NeuralFlux** [comment]
Also, the `closes #issue` should be in the message, not the commit. For eg. The way I edited your comment for this PR.

**Comment by ayush1999guptA** [comment]
Sorry I forgot to push my changes

**Comment by NeuralFlux** [comment]
Great work on the registration and validation of emails there! But the email registration wasn't how it was supposed to be. So I removed it from this PR message. I'll just update the issue to make it clearer about what's to be done.

**Pull request merged**
