### PR TITLE
Created BaseApp

### PR DESCRIPTION
**Pull request by vedangj044**
- [ ] closes: #23 

- [ ] closes: #24 

- [ ] closes: #25 

- [x] pep8  

Changes Summary:

- Created BaseApp as proposed in #23 
- Removed redirection to `users`
- Created a Basis home page in `baseApp\templates\baseApp`

### CODE REVIEW

**Comment by vedangj044** [comment]
I think, @NeuralFlux You have not added the Pep8 checking app, yet. I request you to review this pull request. Then we can create another issue to check your entire code for pep8 errors and commit a pep8 compliant code. Once our code passes all pep8 tests, we can configure the pep8 bot on this repo.

**Comment by vedangj044** [comment]
Ignore my previous comments or gitter messages. I am always in a hurry :-) 

Kindly, review this pull request

**Comment by svp19** [comment]
@vedangj044... I was going through your PR :).
- Can you please remove the __pycache__ files and commit. 

Also because the others are not too active now, @NeuralFlux  will be ready to merge your PR if he finds it proper. However, when others began to submit their PRs, merging a PR like this that closes 3 issues can become quite a task. So please try to submit smaller prs that fix One issue at most.

**Comment by vedangj044** [comment]
Sorry for late commit. 
Removed pycached
This should also close 

- [ ] closes #26

**Comment by vedangj044** [comment]
@svp19 OK, as i assigned both the issue, so i submitted one pull request for both of them.

**Comment by NeuralFlux** [comment]
Please try not to reference multiple issues in a PR. It is kind of tough for us to keep a track of each issue. I've edited your comment to remove the 26 issue mention. You can do it in a different PR if interested. For now, this looks good enough to be merged.

**Pull request merged**
