### PR TITLE
profile model created

### LINKED ISSUE #17: Create a Profile Model
Every user would require his own Profile. Create a ProfileModel in `users/models.py`

Some fields he would require include 
- date of birth
- description
- profile_image
Don't forget to add a OneToOneField to users

Do add more cool fields that you think might be important!

### PR DESCRIPTION
**Pull request by ayush1999guptA**
- [x] Closes #17 
*****************
Changes summary:
as per a good first issue I created a profile model in users/model.py

### CODE REVIEW

**Comment by NeuralFlux** [comment]
Thanks for the PR, @ayush1999guptA . We also need a OneToOneField in the profile to link every user to their unique profile. Watching [this](https://www.youtube.com/watch?v=FdVuKt_iuSI) will surely help!

**Comment by ayush1999guptA** [comment]
I have created a OneToOne field in the ProfileModel

**Comment by NeuralFlux** [comment]
The DOB field has a small glitch I feel, can you put default as blank? Because it'll be more odd to see someone's DOB as a recent date :stuck_out_tongue_closed_eyes: when compared to seeing a blank field there.

**Comment by ayush1999guptA** [comment]
done

**Comment by NeuralFlux** [comment]
Alrighty, merging it

**Pull request merged**
